### ISSUE TITLE
kernel gives wrong values in /proc/loadavg

### ISSUE THREAD

**Issue by HSTe** [imx6-dongle/linux-imx#11]
There is something wrong in how it calculate the values.
Even when cpu is idling it has a loadavg over 4

**Comment by projectgus** [comment]
The majority of this is fixed with commit b8a4b014ead3840271b00948b4970051b13e4ff2 (currently part of #15.) There were 4 IPU tasks running in uninterruptable sleep, thereby inflating the load average by 4.

The commit switches them to interruptible which I think is a harmless change unless the kernel decides to kill them, which is should probably be allowed to do anyhow.

That said, idle load averages are still high (0.5-0.7 sometimes when I'd expect close to 0.) I don't have an explanation for this, I think something with softirqs. Still, &lt;1 is much better than &gt;4. :)
- Angus

**Comment by abrasive** [comment]
<3

**Comment by abrasive** [comment]
Merged #15.
